### ISSUE TITLE
Ports module stabilization todo

### ISSUE THREAD

**Issue by Yohe-Am** [metatypedev/ghjk#25]
- [ ] Formalize runtime dependencies
- [ ] Optional port dependencies
  - Currently, the deps the ports needs to do it's thing are listed in it's manifest. What's more, a port's install config can specify install configs for it's deps. I expect implementing optional deps will fall somewhere between the two.
- [ ] Installation sets. Build this on top of #24  
- [ ]  Sandboxing #9
  - [ ] Prevent Ports from reading the environment
    - They can instead use their `conf` function to read the environment during serialization and add what they need to their `InstallConfig` .
    - This will make it more syncing more deterministic.
    - Formalizing this for easy overriding will be nice.
